### ISSUE TITLE
Purpose of creating this repository?

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/AMX-Mod-X-Autoupdate#1]
I don't really understand why this repository is created, it doesn't serve any purpose for OGP currently.

**Comment by DieFeM** [comment]
It is part of a contribution for updating a popular game-server mod. As precaution I decided to move the source to our repositroy, in case of deletion of the original source, or injecting malicious code by an "updated" version, in short, to keep it under our control.

The alternative was just removing the contribution for the lack of security. On the other hand I don't think having this repository hurts. https://opengamepanel.org/forum/viewthread.php?thread_id=7864

**Comment by Zorrototo** [comment]
Alright :+1:
